version: '2'
services:
  S3:
    image: adobe/s3mock
    ports:
      - '9090:9090'
      - '9191:9191'
    environment:
      initialBuckets: 's3_ecto_test,s3_ecto_test_2'
      root: /data
    volumes:
      - ./_s3:/data
  MySQL:
    image: mysql:5.6
    ports:
      - '3306:3306'
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 's3_ecto_test'
    volumes:
      - ./_mysql:/var/lib/mysql
